In [2]:
import numpy as np

In [3]:
asList = [1,2,3]
asArray = np.array([1,2,3]) #1D array
rowVec = np.array([[1,2,3]]) # row
colVec = np.array([[1],[2],[3]]) #col

In [7]:
for item in (asArray,rowVec,colVec):
    print(type(item))
    print(item.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(1, 3)
<class 'numpy.ndarray'>
(3, 1)


In [11]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])

vPlusW = v+w
#uPlusW = u+w #error! dimensions mismatched
print(f'vPlusW : {vPlusW},{type(vPlusW)}')

vPlusW : [14 25 36],<class 'numpy.ndarray'>


In [19]:
#adding a row and a column vector
v = np.array([[4,5,6]]) #a row vector
u = np.array([[10],[20],[30]]) # col vector
print(f'shapes of v and u: {v.shape}, {u.shape}')
v+w
#normally this would result in a broadcast result

shapes of v and u: (1, 3), (3, 1)


array([[14, 25, 36]])

In [14]:
#trying a multiple transpose:
v = np.array([[1,2,3,4,5]]) #a row vector
for i in range(3):
    print(f'shape of v before {i} transpose operation: {v.shape}')
    v = v.T

shape of v before 0 transpose operation: (1, 5)
shape of v before 1 transpose operation: (5, 1)
shape of v before 2 transpose operation: (1, 5)


In [16]:
v = np.array([[1,2,3]]).T #col vector
u = np.array([[10,20]]) # row vector
v+u # additon with broadcasting

array([[11, 21],
       [12, 22],
       [13, 23]])

In [23]:
#getting the magnitude of a vector
v = np.array([1,2,3,7,8,9])
v_dim = len(v) #math dimensionality
v_mag = np.linalg.norm(v) #math magnitude, length or norm
print(f'the mathemtical dimensionality: {len(v)}\n The norm or magnitude {np.linalg.norm(v)}')
#to get the unit vector in the same direction as v:
v_cap = v/v_mag
print(f'the lenght of the unit vector v_cap:{np.linalg.norm(v_cap)}')

the mathemtical dimensionality: 6
 The norm or magnitude 14.422205101855956
the lenght of the unit vector v_cap:1.0


In [29]:
#the vector dot product
v = np.array([1,2,3,4])
w = np.array([5,6,7,8])
u = np.array([13,21,34,12])

#the dot product is distributive
res1 = np.dot(v,u+w)
res2 = np.dot(v,u) + np.dot(v,w)
print(f'res1: {res1}, res2: {res2}')

res1: 275, res2: 275


In [31]:
#how does the normal product operator work?
#It results in Haddamard multiplication: just element wise mulitplication
a = np.array([5,8,2])
b = np.array([1,0,.5])
a*b

array([5., 0., 1.])

In [ ]:
#Outer product- create a matrix from a column and row vector
# each row in the outer product matrix is the row vector scalar multiplied
# by the corresponding element in the column vector.
